// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUQcWqxDO0yYnQ6EOPW5tmTeCJXnUY1Y',
    appId: '1:751722317038:web:588b11733e348a94f5dfff',
    messagingSenderId: '751722317038',
    projectId: 'fir-wealingo',
    authDomain: 'fir-wealingo.firebaseapp.com',
    storageBucket: 'fir-wealingo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpnqfkgWCSrtncIyCen1ZTAQsZDtEIryU',
    appId: '1:751722317038:android:feb82a21cb5a3a56f5dfff',
    messagingSenderId: '751722317038',
    projectId: 'fir-wealingo',
    storageBucket: 'fir-wealingo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYd7n1nXXZC_AmxgpFpHkDS-YsqJMkqU',
    appId: '1:751722317038:ios:8887a3181de5d1d0f5dfff',
    messagingSenderId: '751722317038',
    projectId: 'fir-wealingo',
    storageBucket: 'fir-wealingo.appspot.com',
    iosBundleId: 'tdtu.flutter.duolingo',
  );
}
